### ISSUE TITLE
Premission denied

### ISSUE THREAD

**Issue by Ser202** [Guad/GTACoop#10]
Hello Guadmaz,

I got an Issue, because of that im contacting you,  when ever I want to join a Server/ or use Server Browser, then I get the message: " The connection of the remoteserver cant be reached."
And looked up the log of ScriptHookVDotNet, but can't really understand the issue, I will post the link here and I hope you can understand it.

http://pastebin.com/bQbu318N

**Comment by Barnsen** [comment]
Check your firewall/antivirus.

**Comment by MaZyGer** [comment]
Log translation

> System.Net.WebException: The connection to remoteserver cannot be established. ---> System.Net.Sockets.SocketException: Access to the socket was due to the access rights illegal 46.101.1.92:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

**Comment by Ser202** [comment]
I deactivated the firewall. Before I did it, I tried to open the ports and now it works.

**Comment by Barnsen** [comment]
What was the solution @Ser202 ?
