### ISSUE TITLE
Police mod

### ISSUE THREAD

**Issue by trueshotkyle** [Guad/GTACoop#60]
Help my friend and I are trying to play lcpdfr together and we don't see traffic and we only see the call that we get and we don't see the other players perp or person hes chasing

**Comment by trueshotkyle** [comment]
Also we cant get in the same car and stuff

**Comment by FlaggedBrad** [comment]
Push G to get in another player's car. 
Enable the "share world" option in your settings.

**Comment by FlaggedBrad** [comment]
Please Post a comment and mark this thread as closed or fixed if you have no more further questions

**Comment by trueshotkyle** [comment]
Ok thank you I will try it when rage hook gets fixed!
