### ISSUE TITLE
SHDotNet.log Error

### ISSUE THREAD

**Issue by ThatIsMiyu** [Guad/GTACoop#61]
I Installed Co-Op Mod With ScriptHook And ScriptHookVDotNet
I'm Using Win 10, My Windows Has Visual Studio C++ 2013 Installed
When I  Play MY Game Sounds Like Hurt, And *IYKWIM, and some messages shows up in my screen, and says 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Class1.onKeyUp(Object sender, KeyEventArgs e)
   at GTA.Script.raise_KeyUp(Object value0, KeyEventArgs value1)
   at GTA.Script.MainLoop()

**Comment by Guad** [comment]
Post the whole log

**Comment by ThatIsMiyu** [comment]
[scripthookvdotnet-2016-06-09.log .txt](https://github.com/Guad/GTACoop/files/306700/scripthookvdotnet-2016-06-09.log.txt)

**Comment by Guad** [comment]
You haven't placed any coop files in the scripts folder. That error is unrelated

**Comment by ThatIsMiyu** [comment]
I have placed it

**Comment by Guad** [comment]
It's not on the log. Try removing everything from the scripts folder but the coop mod

**Comment by ThatIsMiyu** [comment]
ow i placed it at root folder
