### ISSUE TITLE
Server Browser dont work :( 

### ISSUE THREAD

**Issue by FazerGR** [Guad/GTACoop#64]
My server browser dont work. ScriptHookVDotNet log : http://pastebin.com/GgUX5etL

**Comment by Guad** [comment]
Try again in 5 minutes

**Comment by FazerGR** [comment]
still dont work

**Comment by Bluscream** [comment]
@FazerGR Check your firewall if GTA5.exe is allowed at all times. Please refer to https://github.com/Guad/GTACoop/wiki/Firewall

**Comment by MaZyGer** [comment]
To make clear.. yesterday it didn't work for me too. I just opened the http ip adress with chrome where you see the list. That worked but not one the client. But I could still connect to my local test server

**Comment by Bluscream** [comment]
Same to you @MaZyGer

**Comment by MaZyGer** [comment]
> Same to you @MaZyGer

I haven't any Firewall behind my system. Thats the problem :D. I disabled it. But I will still try it. I cannot trust windows.

BTW. It was just on 22th july.

EDIT: I can confirm. It works now. Why I need to unblock games.. even with disabled firewall on windows.. lul.
