### ISSUE TITLE
Terrible Sync

### ISSUE THREAD

**Issue by Biochemisery** [Guad/GTACoop#85]
Is it just me or is there terrible sync? There are no animations for movement except jumping and everything is really jittery. 

The vehicle sync is not as bad as the ped sync, but it's still pretty bad,

**Comment by Bluscream** [comment]
The sync of GTACoop was and will probably ever by shitty. It's not really meant for serious gameplay, more for the fun. If you get us some servers with the same specs as the GTA:Online servers this might change. But until you can afford that, wait for Guad's next Multiplayer mod. It will be the official successor of GTACoop and will have a sync that you can compare to FiveReborn.
